<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>Dunia.Toolkit</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Dunia.Formats/Dunia.Formats.csproj" />
  </ItemGroup>
</Project>

